extends: existence
message: "Schema of type 'number' must specify a 'format'."
link: https://github.com/opensearch-project/documentation-website/blob/main/TERMS.md
ignorecase: true
level: warning
action:
  name: remove
tokens:
  - "type: number"
patterns:
  - pattern: 'type: number'
    next_line: 
      - pattern: 'format:'
        negate: true
