extends: existence
message: "Schema of type 'number' must specify a 'format'."
ignorecase: true
level: warning
scope: paragraph
patterns:
  - pattern: '^\s*-?\s*type:\s*number\s*(?:#.*)?$'
    next_line:
      - pattern: '^\s*format:'
        negate: true
