extends: existence
message: "Schema of type 'number' must specify a 'format'."
link: https://github.com/opensearch-project/documentation-website/blob/main/TERMS.md
ignorecase: true
level: warning
action:
  name: remove
raw:
  - '(?m)^\s*-?\s*type:\s*number\s*(?:#.*)?$'
