openapi: 3.1.0
info:
  title: OpenSearch SQL API
  description: OpenSearch SQL API
  version: 1.0.0
paths:
  /_plugins/_sql:
    post:
      operationId: sql.query.0
      x-operation-group: sql.query
      x-version-added: '1.0'
      description: Sends an SQL/PPL query to the SQL plugin. 
      externalDocs:
        url: https://opensearch.org/docs/latest/search-plugins/sql/sql-ppl-api/
      parameters:
        - $ref: '#/components/parameters/sql.query::query.format'
        - $ref: '#/components/parameters/sql.query::query.sanitize'
      requestBody:
        $ref: '#/components/requestBodies/sql.query'
      responses:
        '200':
          $ref: '#/components/responses/sql.query@200'
components:
  parameters:
    sql.query::query.format:
      name: format
      in: query
      description: A short version of the Accept header, e.g. json, yaml.
      schema:
        type: string
        description: A short version of the Accept header, e.g. json, yaml.
    sql.query::query.sanitize:
      name: sanitize
      in: query
      description: Specifies whether to escape special characters in the results
      schema:
        type: boolean
        default: true
        description: A short version of the Accept header, e.g. json, yaml.
  requestBodies:
    sql.query:
      content:
        application/json:
          schema:
            $ref: '../schemas/sql._common.yaml#/components/schemas/SqlQuery'
      required: true
  responses:
    sql.query@200:
      description: ''
      content:
        application/json:
          schema:
            $ref: '../schemas/sql._common.yaml#/components/schemas/SqlResponse'
