openapi: 3.1.0
info:
  title: Schemas of _plugins._common category.
  description: Schemas of _plugins._common category.
  version: 1.0.0
paths: {}
components:
  schemas:
    Query:
      type: object
      properties:
        query:
          type: string
        filter:
          type: object
        fetch_size:
          type: integer
    QueryResponse:
      type: object
      properties:
        schema:
          type: array
          items:
            type: object
        datarows:
          type: array
          items:
            type: array
        cursor:
          type: string
        total:
          type: integer
        size:
          type: integer
        status:
          type: integer
    Explain:
      type: object
      properties:
        query:
          type: string
        filter:
          type: object
        fetch_size:
          type: integer
    ExplainResponse:
      type: object
      properties:
        root:
          $ref: '#/components/schemas/ExplainBody'
    ExplainBody:
      type: object
      properties:
        name:
          type: string
        description:
          type: object
        children:
          type: array
          items: 
            $ref: '#/components/schemas/ExplainBody'
    Stats:
      type: object
      properties:
        start_time:
          type: string
        end_time:
          type: object
        cluster_name:
          type: object
        index:
          type: object
        query:
          type: object
        user:
          type: object
        execution_time:
          type: object