openapi: 3.1.0
info:
  title: Schemas of sql._common category.
  description: Schemas of sql._common category.
  version: 1.0.0
paths: {}
components:
  schemas:
    SqlClose:
      type: object
      properties:
        cursor:
          type: string
    SqlCloseResponse:
      type: object
      properties:
        succeeded:
          type: boolean