openapi: 3.1.0
info:
  title: Schemas of sql._common category.
  description: Schemas of sql._common category.
  version: 1.0.0
paths: {}
components:
  schemas:
    SqlQuery:
      type: object
      properties:
        query:
          type: string
        filter:
          type: object
        fetch_size:
          type: integer
    SqlQueryResponse:
      type: object
      properties:
        schema:
          type: array
          items:
            type: object
        datarows:
          type: array
          items:
            type: array
        cursor:
          type: string
        total:
          type: integer
        size:
          type: integer
        status:
          type: integer
    SqlExplain:
      type: object
      properties:
        query:
          type: string
        filter:
          type: object
        fetch_size:
          type: integer
    SqlExplainResponse:
      type: object
      properties:
        root:
          $ref: '#/components/schemas/Explain'
    Explain:
      type: object
      properties:
        name:
          type: string
        description:
          type: object
        children:
          type: array
          items: 
            $ref: '#/components/schemas/Explain'
    SqlClose:
      type: object
      properties:
        cursor:
          type: string
    SqlCloseResponse:
      type: object
      properties:
        succeeded:
          type: boolean
    SqlStats:
      type: object
      properties:
        start_time:
          type: string
        end_time:
          type: object
        cluster_name:
          type: object
        index:
          type: object
        query:
          type: object
        user:
          type: object
        execution_time:
          type: object
    SqlSettings:
      type: object
      properties:
        transient:
          $ref: '#/components/schemas/Transient'
    SqlSettingsResponse:
      type: object
      properties:
        acknowledged:
          type: boolean
        persistent:
          type: object
        transient:
          $ref: '#/components/schemas/Transient'
    Transient:
      type: object
      properties:
        plugins:
          $ref: '#/components/schemas/Plugins'
    Plugins:
      type: object
      properties:
        ppl:
          $ref: '#/components/schemas/Ppl'
        query:
          $ref: '#/components/schemas/Query'
        sql:
          $ref: '#/components/schemas/Sql'
    Ppl:
      type: object
      properties:
        enabled:
          type: string
    Query:
      type: object
      properties:
        memory_limit:
          type: string
        size_limit:
          type: string

    Sql:
      type: object
      properties:
        enabled:
          type: string
        slowlog:
          type: string
        cursor:
          $ref: '#/components/schemas/Cursor'
    Cursor:
      type: object
      properties:
        keep_alive:
          type: string