openapi: 3.1.0
info:
  title: Schemas of sql._common category.
  description: Schemas of sql._common category.
  version: 1.0.0
paths: {}
components:
  schemas:
    SqlQuery: # Can we name it just Query?
      type: object
      properties:
        query:
          type: string
        filter:
          type: object
        fetch_size:
          type: integer
    SqlQueryResponse:
      type: object
      properties:
        schema:
          type: array
          items:
            type: object
        data_rows:
          type: array
          items:
            type: array
            items:
              type: object
        total:
          type: integer
        size:
          type: integer
        status:
          type: string
    SqlExplain:
      type: object
      properties:
        query:
          type: string
        filter:
          type: object
        fetch_size:
          type: integer
    SqlExplainResponse:
      type: object
      properties:
        root:
          $ref: '#/components/schemas/Explain'
    Explain:
      type: object
      properties:
        name:
          type: string
        description:
          type: object
        children:
          type: array
          items: 
            $ref: '#/components/schemas/Explain'
    SqlClose:
      type: object
      properties:
        cursor:
          type: string
    SqlCloseResponse:
      type: object
      properties:
        succeeded:
          type: boolean
    SqlStats:
      type: object
      properties:
        start_time:
          type: string
        end_time:
          type: object
        cluster_name:
          type: object
        index:
          type: object
        query:
          type: object
        user:
          type: object
        execution_time:
          type: object
    SqlStatsResponse:
      type: object
      properties:
        request_total:
          type: integer
        request_count:
          type: integer
        failed_request_count_syserr:
          type: integer
        failed_request_count_cuserr:
          type: integer
        failed_request_count_cb:
          type: integer